spring:

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration